### ISSUE TITLE
Stencil pack is unusable as there are no stencils.

### ISSUE THREAD

**Issue by erulabs** [rackerlabs/fastfood-templatepack#3]
In addition, there is no base. This renders FastFood totally useless.

Please resolve by accepting Pull Requests or committing stencils.

Thanks!

**Comment by erulabs** [comment]
End of day Thursday February 26th - Still no usable Stencils. Fastfood is unusable. Please update ASAP.

Thanks!

**Comment by dude051** [comment]
The guidelines for contributing are not yet decided on and are being worked on - is the need for this to happen so quickly because this is impacting your ability to service and work on cookbooks?

Your welcome!

**Comment by erulabs** [comment]
I want this to happen quickly because FastFood used to be functional, and currently is not.

The complete accomplishment of this repository and the rewrite of FastFood has been:

a) Timesink
b) Remove access and prevent contributions
c) Delete existing working stencils
d) Paralyze new builds
